name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Instalar AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli

      - name: Criar o bucket S3
        run: |
          aws s3api create-bucket --bucket tech-challenge-tf-state --region us-west-2 --create-bucket-configuration LocationConstraint=us-west-2
        continue-on-error: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          export TF_LOG=DEBUG
          terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
